### ISSUE TITLE
Failing return instruction assertion on Mac

### ISSUE THREAD

**Issue by averynortonsmith** [pointless-lang/pointless#2]
Not sure if this is another Mac-only problem, but I'm also getting this assertion failure when I try to run anything:
```
~/build/pointless % cat hello.ptls
output = println("Hello World!")
~/build/pointless % ./pointless hello.ptls
Assertion failed: (!retInst), function run, file vm/opHandlers.h, line 865.
zsh: abort      ./pointless hello.ptls
```

The 'compile' tests all pass, but most of the 'vm' tests fail with this same error:
```
~/build/pointless % ls tests/vm/*.test.actual | xargs grep -L retInst
tests/vm/funcDupParamErr.test.actual
tests/vm/nameErr.test.actual
tests/vm/objectNameErr.test.actual
tests/vm/tupleNameErr.test.actual
tests/vm/updateFieldDollarErr.test.actual
```

_Originally posted by @dpercy in https://github.com/pointless-lang/pointless/pull/1#issuecomment-610678597_

**Comment by dpercy** [comment]
> Thanks for the changes! I don't have access to a Mac myself so there's still some testing to do there.
> 
> To address the assertion bug: if you look in `./vm/vm.c` at lines 43-44 and replace
> 
> ```
> #define gotoHandler                            \
>   goto *inst->handler;
> ```
> 
> with
> 
> ```
> #define gotoHandler                            \
>   showInstruction(inst, instIndex);            \
>   if (inst->loc) {                             \
>     printLocLine(stdout, inst->loc);           \
>     printLineCaret(stdout, inst->loc->colNum); \
>     printf("\n");                              \
>   }                                            \
>   goto *inst->handler;
> ```
> 
> then rebuild `make pointless` and try re-running the hello world script, you should get a lot of output. If you get the chance to save that to a file and send it to me I can try to use it to root-out the issue. Otherwise I'll try to find a Mac to do some more testing on.

Thanks!  Here's that output: 
https://github.com/pointless-lang/pointless/files/4448204/out.txt  I got identical output running hello world, empty file, and collatz.ptls, so I guess it happens during some kind of setup?  Maybe while executing the prelude?

I also tried compiling + running the tests in an Ubuntu 18 VM and had no problem.

**Comment by averynortonsmith** [comment]
Thanks! I did some more digging as well and it seems to be a bug in the VM around indexing the call-stack. I just got a MacOS VM installed and will look at it some more tomorrow.

**Comment by averynortonsmith** [comment]
Issue should be fixed by latest commit
