### ISSUE TITLE
Explain why pointless isn't so

### ISSUE THREAD

**Issue by Pyrolistical** [pointless-lang/pointless#8]
I couldn't find any documentation on the motivations on pointless and why it was created.

This is the number one thing that will get pointless to catch people's interest.

**Comment by averynortonsmith** [comment]
Here you go! [https://github.com/pointless-lang/pointless/blob/master/why_pointless.md](https://github.com/pointless-lang/pointless/blob/master/why_pointless.md)

I'll put a link to it on the site. Would love to hear any feedback you have. Thanks for the suggestion!

**Comment by Pyrolistical** [comment]
Perfect! Now I understand what you are trying to do. And while I personally disagree with it, that's the purpose of this document! It'll filter people out who are not interested and keep the ones that are.

Me personally, I don't think imperative vs functional is any easier for beginners to understand. The main problem with the current way we program today is we first need to build the computer in our minds, run the code through our mind computer, then we understand what is going on. That to me is so fundamentally limiting when teaching beginners.

IMO, this is why we need an inside-out computer and show beginners how instructions/code changes the state of the computer. If people can see the contents of variables changing as the code runs, this will make everything click.

**Comment by averynortonsmith** [comment]
Interesting perspective. Definitely check out [Python Tutor](http://pythontutor.com/) if you haven't, it tries to do exactly what you describe, for a number of languages.
